### PR TITLE
Clean up various minor issues

### PR DESCRIPTION
**Pull request by pabs3**
Fix various minor issues found by several tools
that are run by the check-all-the-things meta-linter.

### CODE REVIEW

**Comment by sgaraud** [comment]
Great! I did not know that linter. I will merge the pull request asap.

**Comment by sgaraud** [comment]
@pabs3 thanks for the cleanup. I kept the *.mo and gschema.compiled files to keep the installation from source simple.

**Comment by pabs3** [comment]
Why did you squash all the commits and remove me from the authorship
information? I would prefer that you revert the squashed commit and
instead merge my commits individually, preserving the author info.

I think that keeping the generated files just complicates things, since
distros that only build from source will now have to manually clean
those files out so that they can build them from source properly.

Generated files inevitably get out of date so it is much better to
always build them from source instead of embedding in the repo.

**Comment by sgaraud** [comment]
The pull request had conflict to resolve. I will reopen it and merge the commits one by one.

**Pull request merged**
