### PR TITLE
Add option to place in network menu

### PR DESCRIPTION
**Pull request by paddatrapper**
Adds the option for the IP address label to be placed in the network menu instead of the top bar.

This is achieved through two parent classes, each which inherit from their respective GNOME UI base classes. These parent classes contain an instance of the base class, which does the work in manipulating and retrieving the IP address.

### CODE REVIEW

**Comment by sgaraud** [comment]
thank you for that change! I  will check it asap and make a new release including it.

**Comment by paddatrapper** [comment]
@sgaraud any chance to review this?

**Comment by sgaraud** [comment]
thanks for your contribution. I really appreciate it.
I added the french localization. The change will be included in the next update on gnome extension website.
I may change the IP: display in the final v7 as I got some requests to display the interface name.

**Comment by paddatrapper** [comment]
Anytime. This merge means that from the v7, ShowIP will be packaged for Debian Sid and Buster (next but one stable release)

**Pull request merged**
