### PR TITLE
Added v2 functionnalities : ipv6, device rememberance, public ip, pref menu

### PR DESCRIPTION
**Pull request by rigelk**
A detailed list of changes:
- README.md: updated to v3 roadmap. updated line wrap.
- extentsion.js: added imports, notably use of libshell and libsoup. added
  functions related to ipv6, device remenberance, public ip display, pref
  menu opening.
- metadata.json: added schema properties.
- schema/ (new)
- schema/org.gnome.shell.extensions.shew-ip.gschema.xml (new): schema to
  remember data for the app.
- schema/gschema.compiled (new)
- prefs.js (new): configures the preferences window.
- convenience.js (new): helper file to get settings saved in the schema.

Tested with wired, wireless and virtual interfaces. The **only thing still to do** before the V2 is to make the pref window change the PopupMenu without the need of a manual `Alt+F2`.

### CODE REVIEW

**Comment by sgaraud** [comment]
Hello,

Thanks for that! It looks great. I will check and test in details and
include that pull request asap.

Sylvain

**Comment by sgaraud** [comment]
Thanks again. I like the way you implemented the features. It gave me an idea of improvement for the public ip display. And I will work on making the preference changes applied immediately.

**Comment by rigelk** [comment]
Thanks @sgaraud 
Do you have an idea on how to implement that feature? I’ve already looked at the system-monitor-extension pref.js code, so far with no clue though its use shows such a feature at work.

**Comment by sgaraud** [comment]
Honestly I have no idea.  I will also have to dig into the code of other extensions as good documentation on gjs especially for gnome-shell is not easy to find.  plan to spend time on that during the weekend.

**Pull request merged**
